site_name: MooVision

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/@mermaid-js/layout-elk@0.1.7/dist/mermaid-layout-elk.js
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js
  - javascripts/mermaid-init.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            docstring_style: numpy

nav:
  - Home: index.md
  - Model Pipeline:
    - Reading In Data: 
      - Reading In Data: Pipeline/01_read_data/read_all_clips_index.md
      - Matching: Pipeline/01_read_data/matching.md
      - Schema: Pipeline/01_read_data/schema.md
    - Splitting Data: Pipeline/02_split_data/split_data.md
    - Baseline: Pipeline/05_run_models/baseline.md
    - Preprocessing: 
      - Preprocessing: Pipeline/03_preprocessing/preprocessing.md
      - Extract Frames: Pipeline/03_preprocessing/extract_frames.md
      - Extract Labels: Pipeline/03_preprocessing/extract_labels.md
      - Utils: Pipeline/03_preprocessing/utils.md
    - Training:
      - YOLO: Pipeline/04_training/training_yolo.md
    - Evaluation:
      - Model Evaluation: Pipeline/06_evaluation/evaluation.md
      - CS Detection Evaluation: Pipeline/06_evaluation/predict_bboxes.md
    - Clipping: Pipeline/07_generating_clips/clipping.md
    - Analysis: Pipeline/08_analysis/analysis.md
  - Testing: testing/testing.md
  - Utils:
    - Utils: utils/utils.md
    - Sockeye: utils/sockeye.md
  - About:
    - About: about/about.md
    - License: about/license.md
    - Release Notes: about/release_notes.md
