site_name: MooVision

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            docstring_style: numpy

nav:
  - Home: index.md
  - Get Video: get_video.md
  - Evaluation: evaluation.md